v11 = '<p class="MsoNormal">Найдите четырёхзначное натуральное число, кратное 55, все цифры которого различны и&nbsp;нечётны. В ответе запишите какое-нибудь одно такое число.</p>'
v12 = '<p class="MsoNormal">Найдите значение выражения <math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle displaystyle="true"> <semantics> <mrow> <mfrac> <mrow> <mn>49</mn> </mrow> <mrow> <mn>15</mn> </mrow> </mfrac> <mo>:</mo><mrow><mo>(</mo> <mrow> <mfrac> <mn>5</mn> <mn>6</mn> </mfrac> <mo>+</mo><mfrac> <mn>4</mn> <mn>5</mn> </mfrac> </mrow> <mo>)</mo></mrow> </mrow>  </semantics> </mstyle></math xmlns="http://www.w3.org/1998/Math/MathML">.</p>'
v13 = '<p class="MsoNormal">Найдите значение выражения <math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle displaystyle="true"> <semantics> <mrow> <mfrac> <mrow> <msup> <mn>4</mn> <mrow> <mo>&#x2212;</mo><mtext>&#x2009;</mtext><mn>7</mn> </mrow> </msup> <mtext>&#x200B;</mtext><mo>&#x22C5;</mo><msup> <mn>4</mn> <mn>5</mn> </msup> </mrow> <mrow> <msup> <mn>4</mn> <mrow> <mo>&#x2212;</mo><mtext>&#x2009;</mtext><mn>4</mn> </mrow> </msup> </mrow> </mfrac> </mrow>  </semantics> </mstyle></math xmlns="http://www.w3.org/1998/Math/MathML">.<span></span></p>'
v14 = '<p class="MsoNormal">В треугольнике <math xmlns="http://www.w3.org/1998/Math/MathML"> <semantics> <mrow> <mi>A</mi><mi>B</mi><mi>C</mi> </mrow> </semantics> </math xmlns="http://www.w3.org/1998/Math/MathML">&nbsp;угол <math xmlns="http://www.w3.org/1998/Math/MathML"> <semantics> <mi>C</mi> </semantics> </math xmlns="http://www.w3.org/1998/Math/MathML">&nbsp;равен <math xmlns="http://www.w3.org/1998/Math/MathML"> <semantics> <mrow> <mn>90</mn><mi>&#x00B0;</mi><mtext>&#x200B;</mtext><mo>,</mo> </mrow> </semantics> </math xmlns="http://www.w3.org/1998/Math/MathML">&nbsp;<math xmlns="http://www.w3.org/1998/Math/MathML"> <semantics> <mrow> <mi>A</mi><mi>B</mi><mo>=</mo><mn>20,</mn> </mrow> </semantics> </math xmlns="http://www.w3.org/1998/Math/MathML">&nbsp;<math xmlns="http://www.w3.org/1998/Math/MathML"> <semantics> <mrow> <mi>A</mi><mi>C</mi><mo>=</mo><mn>12.</mn> </mrow> </semantics> </math xmlns="http://www.w3.org/1998/Math/MathML">&nbsp;Найдите <math xmlns="http://www.w3.org/1998/Math/MathML"> <semantics> <mrow> <mi>cos</mi><mi>B</mi><mo>.</mo> </mrow> </semantics> </math xmlns="http://www.w3.org/1998/Math/MathML"></p>'

allvar = v11 + '\n' + v12 + '\n' + v13 + '\n' + v14 + '\n'

# print(allvar)
answerbut =  '<button class="file-saver">&#1054;&#1090;&#1074;&#1077;&#1090;&#1080;&#1090;&#1100;</button>'
script = "<script>\nlet egemathprofballs = [6, 11, 17, 22, 27,34,40,46,52,58,64,70,72,74,76,78,80,82,84,86,88,90,92,94,96,97,98,99,100,100,100]\nvar test = 20;\nconst fileSaver$ = document.querySelector('.file-saver')\nconst options = {\n  suggestedName: 'test1.sql',\n  types: [\n   {\n    description: 'Text',\n    accept: {\n    'text/plain': '.sql'\n    }\n   }\n  ],\n excludeAcceptAllOption: true\n}\nconst fileData = \"USE myfirstdb\\;\\nINSERT INTO staff (name, position)\\nvalues('\" + test + \"', '\\n\"+ egemathprofballs[test] + \"')\"\nfileSaver$.addEventListener('click', async () => {\n   alert('Вы решили ' + test + ' заданий и набрали ' + egemathprofballs[test] + ' баллов!');\n  const fileHandle = await window.showSaveFilePicker(options)\n  const writableStream = await fileHandle.createWritable()\n  await writableStream.write(fileData)\n  await writableStream.close()\n})\n</script>"
variant = f'<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>Document</title>\n</head>\n<body>\n<h1>Математика профиль.</h1>\n{allvar}{answerbut}{script}\n</body>\n</html>'
print(variant)
