v11 = '<p class="MsoNormal">Найдите четырёхзначное натуральное число, кратное 55, все цифры которого различны и&nbsp;нечётны. В ответе запишите какое-нибудь одно такое число.</p>'
v12 = '<p class="MsoNormal">Найдите значение выражения <math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle displaystyle="true"> <semantics> <mrow> <mfrac> <mrow> <mn>49</mn> </mrow> <mrow> <mn>15</mn> </mrow> </mfrac> <mo>:</mo><mrow><mo>(</mo> <mrow> <mfrac> <mn>5</mn> <mn>6</mn> </mfrac> <mo>+</mo><mfrac> <mn>4</mn> <mn>5</mn> </mfrac> </mrow> <mo>)</mo></mrow> </mrow>  </semantics> </mstyle></math xmlns="http://www.w3.org/1998/Math/MathML">.</p>'
v13 = '<p class="MsoNormal">Найдите значение выражения <math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle displaystyle="true"> <semantics> <mrow> <mfrac> <mrow> <msup> <mn>4</mn> <mrow> <mo>&#x2212;</mo><mtext>&#x2009;</mtext><mn>7</mn> </mrow> </msup> <mtext>&#x200B;</mtext><mo>&#x22C5;</mo><msup> <mn>4</mn> <mn>5</mn> </msup> </mrow> <mrow> <msup> <mn>4</mn> <mrow> <mo>&#x2212;</mo><mtext>&#x2009;</mtext><mn>4</mn> </mrow> </msup> </mrow> </mfrac> </mrow>  </semantics> </mstyle></math xmlns="http://www.w3.org/1998/Math/MathML">.<span></span></p>'
v14 = '<p class="MsoNormal">В треугольнике <math xmlns="http://www.w3.org/1998/Math/MathML"> <semantics> <mrow> <mi>A</mi><mi>B</mi><mi>C</mi> </mrow> </semantics> </math xmlns="http://www.w3.org/1998/Math/MathML">&nbsp;угол <math xmlns="http://www.w3.org/1998/Math/MathML"> <semantics> <mi>C</mi> </semantics> </math xmlns="http://www.w3.org/1998/Math/MathML">&nbsp;равен <math xmlns="http://www.w3.org/1998/Math/MathML"> <semantics> <mrow> <mn>90</mn><mi>&#x00B0;</mi><mtext>&#x200B;</mtext><mo>,</mo> </mrow> </semantics> </math xmlns="http://www.w3.org/1998/Math/MathML">&nbsp;<math xmlns="http://www.w3.org/1998/Math/MathML"> <semantics> <mrow> <mi>A</mi><mi>B</mi><mo>=</mo><mn>20,</mn> </mrow> </semantics> </math xmlns="http://www.w3.org/1998/Math/MathML">&nbsp;<math xmlns="http://www.w3.org/1998/Math/MathML"> <semantics> <mrow> <mi>A</mi><mi>C</mi><mo>=</mo><mn>12.</mn> </mrow> </semantics> </math xmlns="http://www.w3.org/1998/Math/MathML">&nbsp;Найдите <math xmlns="http://www.w3.org/1998/Math/MathML"> <semantics> <mrow> <mi>cos</mi><mi>B</mi><mo>.</mo> </mrow> </semantics> </math xmlns="http://www.w3.org/1998/Math/MathML"></p>'

allvar = v11 + '\n' + v12 + '\n' + v13 + '\n' + v14 + '\n'

# print(allvar)
answerbut =  '<span class="answer-button" onclick="checkButtonClick(\'checkform496A40\', setAnswer496A40, this.parentNode)">&#1054;&#1090;&#1074;&#1077;&#1090;&#1080;&#1090;&#1100;</span>'
variant = f'<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>Document</title>\n</head>\n<body>\n{allvar}{answerbut}\n</body>\n</html>'
print(variant)
